# Generated by Django 2.2.4 on 2019-09-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190903_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='userid',
            field=models.CharField(default='bkumar', max_length=50),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2019-09-18'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2019-09-18'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
